<a href="https://colab.research.google.com/github/nykolai-d/frequency-of-english-word/blob/main/GetFrequencies.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#from google.colab import drive
#drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
from google.colab import auth
auth.authenticate_user()

import gspread
from google.auth import default
creds, _ = default()

gc = gspread.authorize(creds)

### Sheet of Words

In [ ]:
# Open up workbook
workbook = gc.open_by_url('{##INSERT-GOOGLE-SHEETS-HTML-HERE##}')

In [ ]:
# obtain worksheet titles from workbook
sheet_titles = []
for sheet in workbook.worksheets():
  sheet_titles.append(sheet.title)
sheet_titles

['Step 0: Find Pronunciations',
 'Step 1: Determine Key Syllables',
 'Intermediate Sheet for Calculations',
 'Step 2: Rank Pegs',
 'Step 3: Brainstorm Words Around Pegs',
 'Step 4: Get Frequencies',
 'Step 5: ALINE Score',
 'Step 6: PoS/Orthographic Filter',
 'Step 7: Fragment Screen & Test',
 'Step 8: Permutations',
 'Step 9: Symbol Candidates',
 'Data for Python']

In [ ]:
# Get_all_values from sheets and store in dictionary
dict_of_sheets = {}
for sheet_title in sheet_titles:
  sheet = workbook.worksheet(sheet_title)
  values = sheet.get_all_values()
  dict_of_sheets[sheet_title] = values

# To confirm all sheets made it into the dictionary
dict_of_sheets.keys()

dict_keys(['Step 0: Find Pronunciations', 'Step 1: Determine Key Syllables', 'Intermediate Sheet for Calculations', 'Step 2: Rank Pegs', 'Step 3: Brainstorm Words Around Pegs', 'Step 4: Get Frequencies', 'Step 5: ALINE Score', 'Step 6: PoS/Orthographic Filter', 'Step 7: Fragment Screen & Test', 'Step 8: Permutations', 'Step 9: Symbol Candidates', 'Data for Python'])

In [ ]:
import pandas as pd
df = pd.DataFrame.from_records(dict_of_sheets.get('Step 4: Get Frequencies'))
new_header = df.iloc[0] #grab the first row for the header
df = df[1:] #take the data less the header row
df.columns = new_header #set the header row as the df header
df = df.iloc[: , 1:]
df

,,,,,,,,,,,,,,,,,,,,
1,Symbol 1,Symbol 2,Symbol 3,Symbol 4,Symbol 5,Symbol 6,Symbol 7,Symbol 8,Symbol 9,Symbol 10,Symbol 11,Symbol 12,Symbol 13,Symbol 14,Symbol 15,Symbol 16,Symbol 17,Symbol 18,Symbol 19,Symbol 20
2,mill n' prawn,mill n' ice prawn,Mill Niece prawn,mezzosoprano,,,,,,,,,,,,,,,,
3,aspirin,taciturn,soprano,ice cream,,,,,,,,,,,,,,,,
4,milanese,millionaire,millenial,milano,mayonnaise,illness,mailman,minimal,mimetic,mailman,melodic,malaysia,,,,,,,,
5,prince,suppering,sprain,span,zippering,apron,soprano,supreme,citrons,siberian,citron,cyprian,soprano,stream,strain,screen,scream,,,
6,master,insta,inn,niece,nice,nancy,fancy,nasty,tacit,nazi,nosy,,,,,,,,,
7,milan,NASA,million,milling,melon,manly,minnow,moldy,mildew,malta,milky,malty,mailman,millet,melted,melodic,,,,
8,prawn,pram,prince,bran,cran,dram,plan,ran,ram,rain,rum,rim,mildly,,,,,,,
9,icy,tip,sip,sit,zip,,,,,,,,,,,,,,,
10,mac,mass,maze,,,,,,,,,,,,,,,,,
11,male,milled,meal,milled,miley,millie,mild,milk,mile,mail,mule,,,,,,,,,
12,,,,,,,,,,,,,,,,,,,,

In [ ]:
type(df.iloc[1][1])

str

In [ ]:
df.iat[1, 1]

"mill n' ice prawn"

In [ ]:
df.shape

(12, 20)

### Getting the iWeb Frequency List

In [ ]:
freq = gc.open_by_url('{###LINK-TO-FREQ-DATA###}')
            #Frequency Data from iWeb: https://www.english-corpora.org//iweb/

sheet_titles = []
for sheet in freq.worksheets():
  sheet_titles.append(sheet.title)
dict_of_sheets = {}

for sheet_title in sheet_titles:
  sheet = freq.worksheet(sheet_title)
  values = sheet.get_all_values()
  dict_of_sheets[sheet_title] = values

In [ ]:
df_freq = pd.DataFrame.from_records(dict_of_sheets.get('wordfreq_iWeb'))

new_header = df_freq.iloc[0] #grab the first row for the header
df_freq = df_freq[1:] #take the data less the header row
df_freq.columns = new_header #set the header row as the df header

df_freq.head(5)

0 word       freq
1  the  746240010
2  and  387117884
3   of  345329850
4    a  306826561
5   to  244212028

In [ ]:
list_w = df_freq.to_dict('records')

In [ ]:
list_w[0].get('freq')

'746240010'

In [ ]:
word=str(df.iloc[1][1])
print(word)

mill n' ice prawn

### Get the Frequency of One Word Using df_freq

In [ ]:
#Using data frame iteration
def get_freq(word):
  word_freq=[]
  for i in range(len(df_freq)):
    if(df_freq.iloc[i, 0]==word):
      word_freq.append(word)
      word_freq.append(df_freq.iloc[i, 1])
      break
  return word_freq

In [ ]:
#Using dictionary key-value search
def word_freq(word):
  freq=[]
  for i in range(len(list_w)):
    if(list_w[i].get('word')==word):
      freq.append(word)
      freq.append(list_w[i].get('freq'))
      break
  return freq

In [ ]:
import time

start_time_ns = time.process_time_ns()
get_freq('rope')
end_time_ns = time.process_time_ns()

timer_ns = end_time_ns - start_time_ns
print(timer_ns)

120429635

In [ ]:
#Much quicker!
start_time_ns = time.process_time_ns()
word_freq('rope')
end_time_ns = time.process_time_ns()

timer_ns = end_time_ns - start_time_ns
print(timer_ns)

1641506

### Get Frequencies of Words in Sheet

In [ ]:
df2 = df.copy()

In [ ]:
df2

,,,,,,,,,,,,,,,,,,,,
1,Symbol 1,Symbol 2,Symbol 3,Symbol 4,Symbol 5,Symbol 6,Symbol 7,Symbol 8,Symbol 9,Symbol 10,Symbol 11,Symbol 12,Symbol 13,Symbol 14,Symbol 15,Symbol 16,Symbol 17,Symbol 18,Symbol 19,Symbol 20
2,mill n' prawn,mill n' ice prawn,Mill Niece prawn,mezzosoprano,,,,,,,,,,,,,,,,
3,aspirin,taciturn,soprano,ice cream,,,,,,,,,,,,,,,,
4,milanese,millionaire,millenial,milano,mayonnaise,illness,mailman,minimal,mimetic,mailman,melodic,malaysia,,,,,,,,
5,prince,suppering,sprain,span,zippering,apron,soprano,supreme,citrons,siberian,citron,cyprian,soprano,stream,strain,screen,scream,,,
6,master,insta,inn,niece,nice,nancy,fancy,nasty,tacit,nazi,nosy,,,,,,,,,
7,milan,NASA,million,milling,melon,manly,minnow,moldy,mildew,malta,milky,malty,mailman,millet,melted,melodic,,,,
8,prawn,pram,prince,bran,cran,dram,plan,ran,ram,rain,rum,rim,mildly,,,,,,,
9,icy,tip,sip,sit,zip,,,,,,,,,,,,,,,
10,mac,mass,maze,,,,,,,,,,,,,,,,,
11,male,milled,meal,milled,miley,millie,mild,milk,mile,mail,mule,,,,,,,,,
12,,,,,,,,,,,,,,,,,,,,

In [ ]:
df2.values[1,1]=get_freq(df2.iat[1,1])

In [ ]:
def get_freq_df(df):
  for row in range(len(df)):
    for col in range(len(df.columns)):
      df.values[row,col] = word_freq(df.iat[row,col])
  return df

In [ ]:
df_freq = get_freq_df(df2)

In [ ]:
df_freq

,,,,,,,,,,,,,,,,,,,,
1,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
2,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
3,"[aspirin, 46731]",[],"[soprano, 20981]",[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
4,"[milanese, 1745]","[millionaire, 35186]",[],[],"[mayonnaise, 17841]","[illness, 398394]","[mailman, 5105]","[minimal, 317435]","[mimetic, 1525]","[mailman, 5105]","[melodic, 33064]",[],[],[],[],[],[],[],[],[]
5,"[prince, 396000]",[],"[sprain, 9267]","[span, 131266]",[],"[apron, 39094]","[soprano, 20981]","[supreme, 385393]",[],"[siberian, 17477]","[citron, 1429]",[],"[soprano, 20981]","[stream, 436149]","[strain, 184413]","[screen, 1782180]","[scream, 49316]",[],[],[]
6,"[master, 1193000]",[],"[inn, 164228]","[niece, 42266]","[nice, 2242209]",[],"[fancy, 165910]","[nasty, 159852]","[tacit, 9755]","[nazi, 95356]","[nosy, 5397]",[],[],[],[],[],[],[],[],[]
7,[],[],"[million, 3130513]","[milling, 29458]","[melon, 22615]","[manly, 24365]","[minnow, 4212]","[moldy, 6915]","[mildew, 30608]",[],"[milky, 43782]","[malty, 4614]","[mailman, 5105]","[millet, 13610]","[melted, 68441]","[melodic, 33064]",[],[],[],[]
8,"[prawn, 8192]","[pram, 10953]","[prince, 396000]","[bran, 33300]",[],"[dram, 14306]","[plan, 2602649]","[ran, 698007]","[ram, 258397]","[rain, 551112]","[rum, 67090]","[rim, 156248]","[mildly, 39835]",[],[],[],[],[],[],[]
9,"[icy, 53588]","[tip, 545857]","[sip, 77212]","[sit, 908629]","[zip, 163688]",[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
10,"[mac, 197327]","[mass, 442384]","[maze, 44537]",[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]
11,"[male, 472491]","[milled, 12975]","[meal, 658480]","[milled, 12975]",[],[],"[mild, 268088]","[milk, 745063]","[mile, 427625]","[mail, 680103]","[mule, 34066]",[],[],[],[],[],[],[],[],[]
12,[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[],[]

In [ ]:
#now write this new df to a new sheet in the original google doc

In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.0.10)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)

In [ ]:
# backup the resulting df to an excel file (this step won't be necessary once it has been written to the original google sheet)
with pd.ExcelWriter('df_freq.xlsx') as writer:
    df_freq.to_excel(writer, sheet_name='FreqCount')